"""Constants for TP-Link Local."""

DOMAIN = "tapo_local"
NAME = "TP-Link Local"

CONF_POLL_INTERVAL = "poll_interval"
CONF_TRANSPORT = "transport"
CONF_SESSION = "session"

TRANSPORT_XOR = "xor"
TRANSPORT_DLKLAP = "dlklap"

DEFAULT_PORT = 9999
DEFAULT_TIMEOUT = 5.0
DEFAULT_POLL_INTERVAL = 5
DEFAULT_LOCK_POLL_INTERVAL = 30
MIN_POLL_INTERVAL = 2
MAX_POLL_INTERVAL = 300

SUPPORTED_DEVICE_TYPES = {"IOT.SMARTPLUGSWITCH"}
SUPPORTED_MODELS = {"KS200", "KS200M"}

PIR_MODULE = "smartlife.iot.PIR"

DL100_SESSION_IMPORT = ".storage/tapo_local_dl100_session_import.json"
DL100_SESSION_STORE_VERSION = 1
